/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alliancecontractmanager.gui.panel.mainpanel;

import alliancecontractmanager.db.entities.UserApiEntity;
import alliancecontractmanager.logic.enumname.StatusEnum;
import alliancecontractmanager.logic.manager.ManagerRemainingShips;
import alliancecontractmanager.logic.remainingships.RemainingShips;
import java.beans.Beans;
import java.util.List;
import java.util.Map;

/**
 *
 * @author lele
 */
public class ShowRemainShipsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShowRemainShips
     */
    public ShowRemainShipsJPanel() {
        initComponents();
        if ( Beans.isDesignTime()){
            
        }
        
        jComboBoxStatusContract02.addItem(StatusEnum.COMPLETED.getStatus());
        jComboBoxStatusContract02.addItem(StatusEnum.OUTSTADING.getStatus());
//        ManagerRemainingShips.getInstance().tempDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxUserModel1 = new alliancecontractmanager.gui.mr.model.JComboBox.JComboBoxUserModel();
        jComboBoxUserRenderer1 = new alliancecontractmanager.gui.mr.renderer.jcombobox.JComboBoxUserRenderer();
        showRemainjTableOutstadingModel1 = new alliancecontractmanager.gui.mr.model.jtable.JTableShowRemainOutstadingModel();
        ShowRemainJTableCompleted = new javax.swing.JTable();
        ShowRemainjTableOutstading = new javax.swing.JTable();
        javax.swing.JComboBox<UserApiEntity> jComboBoxUser03 = new javax.swing.JComboBox<>();
        jComboBoxStatusContract02 = new javax.swing.JComboBox<>();
        jPanel_ShowRemainShipContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jComboBoxUserRenderer1.setText("jComboBoxUserRenderer1");

        ShowRemainJTableCompleted.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        ShowRemainjTableOutstading.setModel(showRemainjTableOutstadingModel1);

        jComboBoxUser03.setModel(jComboBoxUserModel1);
        jComboBoxUser03.setRenderer(jComboBoxUserRenderer1);

        jComboBoxStatusContract02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusContract02ActionPerformed(evt);
            }
        });

        jPanel_ShowRemainShipContainer.setBackground(new java.awt.Color(225, 43, 43));

        jScrollPane1.setBackground(new java.awt.Color(231, 229, 59));

        javax.swing.GroupLayout jPanel_ShowRemainShipContainerLayout = new javax.swing.GroupLayout(jPanel_ShowRemainShipContainer);
        jPanel_ShowRemainShipContainer.setLayout(jPanel_ShowRemainShipContainerLayout);
        jPanel_ShowRemainShipContainerLayout.setHorizontalGroup(
            jPanel_ShowRemainShipContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ShowRemainShipContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel_ShowRemainShipContainerLayout.setVerticalGroup(
            jPanel_ShowRemainShipContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ShowRemainShipContainerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_ShowRemainShipContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxUser03, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxStatusContract02, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(0, 177, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUser03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxStatusContract02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_ShowRemainShipContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxStatusContract02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusContract02ActionPerformed
        int selectedItem = this.jComboBoxStatusContract02.getSelectedIndex();
        
        switch (selectedItem){
            case 0:
                Map < String, RemainingShips > doctrineCompletedMap =
                 ManagerRemainingShips.getInstance().getDoctrineCompletedMap();
                writeValueToTable(doctrineCompletedMap, selectedItem);
                break;
            case 1:
                Map < String, RemainingShips > doctrineOutstandingMap =
                 ManagerRemainingShips.getInstance().getDoctrineOutstandingMap(); 
                writeValueToTable(doctrineOutstandingMap, selectedItem);
                break;
        }        
    }//GEN-LAST:event_jComboBoxStatusContract02ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jScrollPane1.setViewportView(this.ShowRemainJTableCompleted);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.jScrollPane1.setViewportView(this.ShowRemainjTableOutstading);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Write Value To jTable in ShowRemainShipsJPanel
     * @param 
     */
    private void writeValueToTable( Map < String, RemainingShips > doctrineMap, int index  ){
        switch (index){
            case 0:
//                writeValueToTableOutstanding(doctrineMap);
            case 1:
                writeValueToTableOutstanding(doctrineMap);
                break;
        }
    }

    private void writeValueToTableOutstanding( Map < String, RemainingShips > doctrineMap){
        showRemainjTableOutstadingModel1.clear();
        
        for (Map.Entry<String, RemainingShips> entry : doctrineMap.entrySet()) {
            showRemainjTableOutstadingModel1.addContract(entry.getValue());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ShowRemainJTableCompleted;
    private javax.swing.JTable ShowRemainjTableOutstading;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxStatusContract02;
    private alliancecontractmanager.gui.mr.model.JComboBox.JComboBoxUserModel jComboBoxUserModel1;
    private alliancecontractmanager.gui.mr.renderer.jcombobox.JComboBoxUserRenderer jComboBoxUserRenderer1;
    private javax.swing.JPanel jPanel_ShowRemainShipContainer;
    private javax.swing.JScrollPane jScrollPane1;
    private alliancecontractmanager.gui.mr.model.jtable.JTableShowRemainOutstadingModel showRemainjTableOutstadingModel1;
    // End of variables declaration//GEN-END:variables
}
